<?php
require __DIR__ . '/../app/helpers/bootstrap.php';
require __DIR__ . '/../app/vendor/fake-vendor/unsafe-helper/Helper.php';
use FakeVendor\UnsafeHelper\Helper;

$route = $_GET['route'] ?? 'home';
if ($route === 'logout') { $logoutUser=telemetry_user(); app_event('logout','authentication','success','User signed out.',['user'=>$logoutUser]); session_destroy(); setcookie('remember_lab','',time()-3600,'/'); header('Location: /'); exit; }

if ($route === 'api-invoice') {
    header('Content-Type: application/json');
    if (!isset($_GET['id'])) {
        http_response_code(500);
        app_event('application_exception','application','error','Invoice API missing required identifier.',['route'=>'api-invoice','http_status'=>500,'owasp_category'=>'A10']);
        echo json_encode(['error'=>'MissingArgumentException: invoice id required','file'=>'/var/www/vulnforge/public/index.php','line'=>214,'debug'=>app_setting('api_exception_marker')], JSON_PRETTY_PRINT);
        exit;
    }
    $stmt=db()->prepare('SELECT id,user_id,invoice_number,item_summary,amount,payment_status,private_note FROM invoices WHERE id=?');
    $stmt->execute([$_GET['id']]); $invoice=$stmt->fetch();
    if($invoice){
        $apiUser=telemetry_user();
        app_event('invoice_view','finance','success','Invoice API record viewed; invoice_id='.(int)$invoice['id'],['user'=>$apiUser,'route'=>'api-invoice']);
        if($apiUser && (int)$invoice['user_id'] !== (int)$apiUser['id']) app_event('invoice_idor_suspected','authorization','observed','Requested invoice owner does not match session user; invoice_id='.(int)$invoice['id'].' owner_user_id='.(int)$invoice['user_id'],['user'=>$apiUser,'route'=>'api-invoice','owasp_category'=>'A01']);
        unset($invoice['user_id']);
    }
    echo json_encode($invoice ?: ['error'=>'not found'], JSON_PRETTY_PRINT); exit;
}

render_header(ucwords(str_replace('-', ' ', $route)));

switch ($route) {
case 'home':
    echo '<section class="hero"><div class="hero-content"><p class="pill">Northstar employee workspace</p><h1>One portal for the trail ahead.</h1><p class="lead">Coordinate outdoor product operations, wholesale accounts, support requests, and internal services from Northstar Outfitters’ private employee hub.</p><div class="button-row"><a class="button" href="/?route=login">Access employee portal</a><a class="button ghost" href="/?route=diagnostics">View system status</a></div></div></section>';
    echo '<div class="grid"><section class="card feature-card"><span class="feature-icon">PO</span><h2>Product operations</h2><p>Review fictional outdoor equipment, warehouse SKUs, pricing, and catalog notes for retail support.</p><a href="/?route=products">Open product catalog →</a></section><section class="card feature-card"><span class="feature-icon">CS</span><h2>Customer support</h2><p>Manage fake employee and wholesale account requests through a centralized helpdesk workflow.</p><a href="/?route=login">Enter support workspace →</a></section><section class="card feature-card"><span class="feature-icon">TR</span><h2>Security readiness</h2><p>Complete 20 OWASP-aligned training objectives woven into everyday portal workflows.</p><!-- FLAG LOCATIONS VARY: comments, records, files, metadata, APIs, logs, and debug output. --><a href="/?route=login">Continue training →</a></section></div>';
    echo '<section class="card"><div class="card-header"><div><p class="eyebrow">Company bulletin</p><h2>Operations update</h2></div>'.status_badge('Active').'</div><p>Spring distribution planning is underway across Operations, Sales, Support, Finance, IT, and Warehouse teams. Staff should verify account details and review open service requests before the next fictional fulfillment cycle.</p><p class="muted">Published by Internal Communications · Training content only</p></section>';
    break;
case 'login':
    $message='';
    if ($_SERVER['REQUEST_METHOD']==='POST') {
        $stmt=db()->prepare('SELECT users.*,roles.name role_name FROM users JOIN roles ON roles.id=users.role_id WHERE email=?'); $stmt->execute([$_POST['email'] ?? '']); $row=$stmt->fetch();
        if ($row && md5($_POST['password'] ?? '') === $row['password_hash']) {
            $_SESSION['user_id']=$row['id'];
            if (!empty($_POST['remember'])) setcookie('remember_lab',base64_encode('user:'.$row['id']),time()+86400*30,'/');
            // The fake in-app audit trail intentionally omits authentication; host telemetry remains separate.
            app_event('login_success','authentication','success','User authentication succeeded.',['user'=>$row]);
            header('Location: /?route=dashboard'); exit;
        }
        app_event('login_failure','authentication','failure','User authentication failed; password and submitted identifier omitted.');
        $message='<div class="error" role="alert"><strong>Sign-in unsuccessful.</strong><br>Check the fictional account details and try again. Detailed failures are intentionally not recorded.</div>';
    }
    echo '<section class="login-shell"><div class="login-aside"><div><a class="brand" href="/?route=home"><img src="/assets/img/northstar-mark.svg" alt="" width="44" height="44"><span><strong>Northstar Outfitters</strong><small>Internal Operations Portal</small></span></a><p class="eyebrow" style="color:#8fc9c2;margin-top:3rem">Employee access</p><h1>Welcome back to the trail team.</h1><p>Access invoices, customer support, catalog operations, account tools, and internal diagnostics.</p></div><div class="company-notice"><strong>Authorized training use only</strong><br>This fictional company portal is restricted to the private VulnForge lab. Never reuse these credentials elsewhere.</div></div><div class="login-panel"><p class="eyebrow">Secure workspace</p><h2>Employee sign in</h2><p class="muted">Use a fake Northstar training account to continue.</p>'.$message.'<form method="post"><label for="email">Work email</label><input id="email" name="email" type="email" autocomplete="username" placeholder="name@northstar.local" required><span class="form-help">Enter your assigned fictional Northstar email.</span><label for="password">Password</label><input id="password" name="password" type="password" autocomplete="current-password" required><span class="form-help">Training credentials are listed in the player guide.</span><label class="checkbox-label"><input type="checkbox" name="remember" value="1"> Keep this private lab browser signed in for 30 days</label><button type="submit">Sign in to portal</button></form></div></section>';
    break;
case 'dashboard':
    $u=require_login();
    page_header('Welcome back, '.$u['display_name'], 'Employee dashboard', 'Your Northstar workspace for customer, finance, and operational activity.');
    echo '<div class="grid"><section class="card stat-card"><span class="stat-label">Account role</span><span class="stat-value">'.h(ucwords($u['role_name'])).'</span><span class="stat-meta">Current directory assignment</span></section><section class="card stat-card"><span class="stat-label">Portal status</span><span class="stat-value">Operational</span><span class="stat-meta">Core local services available</span></section><section class="card stat-card"><span class="stat-label">Training objectives</span><span class="stat-value">20</span><span class="stat-meta">Across 10 OWASP categories</span></section></div>';
    echo '<div class="grid">';
    card('Finance workspace','<p>Review fictional purchases, balances, and payment records.</p><a class="quick-link" href="/?route=invoices"><span>View my invoices</span></a>','accent');
    card('Support desk','<p>Follow account requests and internal helpdesk updates.</p><a class="quick-link" href="/?route=support"><span>Open ticket queue</span></a>','accent');
    card('Employee profile','<p>Maintain your directory biography and profile exports.</p><a class="quick-link" href="/?route=profile"><span>Manage profile</span></a>','accent');
    card('Document exchange','<p>Transfer fictional operational documents inside the lab.</p><a class="quick-link" href="/?route=uploads"><span>Open file exchange</span></a>','accent');
    if ($u['email']==='admin@northstar.local') card('Deployment notice','<p>Factory administrator setup remains active for this training environment.</p><span class="flag">FLAG{A07_DEFAULT_ADMIN_01}</span>','accent');
    if (!empty($_SESSION['remember_restored'])) card('Session notice','<p>A remembered browser session was restored using the local portal token.</p><span class="flag">'.h(app_setting('remember_marker')).'</span>','accent');
    echo '</div><section class="card"><div class="card-header"><div><h2>Internal announcements</h2><p>Updates from Northstar operations teams</p></div>'.status_badge('Active').'</div><div class="service-row"><div><strong>Warehouse cycle count</strong><span>Operations · Fictional western distribution center</span></div><span class="muted">This week</span></div><div class="service-row"><div><strong>Wholesale support coverage</strong><span>Support · Queue coverage extended for training exercises</span></div><span class="muted">Ongoing</span></div></section>';
    break;
case 'products':
    $q=$_GET['q'] ?? '';
    if ($q !== '') {
        // Deliberate SQL injection challenge: local fake catalog only.
        $sql="SELECT id,sku,name,description,price,internal_note FROM products WHERE name LIKE '%$q%' OR description LIKE '%$q%'";
        $pattern=log_suspicious_parameter('q',$q,'products');
        try { $products=db()->query($sql)->fetchAll(); } catch(Throwable $e) { $products=[]; app_event('application_exception','application','error','Catalog query exception class='.get_class($e),['route'=>'products','owasp_category'=>'A10']); echo '<div class="error">Catalog query error: '.h($e->getMessage()).'</div>'; }
        app_event('product_search','catalog','success','Catalog search completed; query omitted, length='.strlen($q).' results='.count($products).' suspicious_pattern='.($pattern??'none'),['route'=>'products']);
    } else $products=db()->query('SELECT id,sku,name,description,price,NULL internal_note FROM products')->fetchAll();
    page_header('Product catalog', 'Merchandising', 'Look up fictional outdoor equipment, customer-facing descriptions, and current list pricing.');
    echo '<form class="search-form"><input type="hidden" name="route" value="products"><div><label for="catalog-q">Search catalog</label><input id="catalog-q" name="q" value="'.h($q).'" placeholder="Try lantern, pack, or trail"><span class="form-help">Search by product name or description.</span></div><button>Search products</button></form><section class="card"><div class="card-header"><div><h2>Catalog results</h2><p>'.h(count($products)).' fictional product'.(count($products)===1?'':'s').' available</p></div></div><div class="table-wrap"><table><thead><tr><th>SKU</th><th>Product</th><th>List price</th><th>Action</th></tr></thead><tbody>';
    foreach($products as $p) echo '<tr><td><code>'.h($p['sku']).'</code></td><td><span class="table-title">'.h($p['name']).'</span><span class="table-subtitle">'.h($p['description']).'</span>'.($p['internal_note']?'<br><code>'.h($p['internal_note']).'</code>':'').'</td><td class="amount">$'.h($p['price']).'</td><td><a class="button ghost small" href="/?route=product&id='.h($p['id']).'">View item</a></td></tr>';
    if (!$products) echo empty_table_row(4, 'No products found', 'Try a broader catalog search term.');
    echo '</tbody></table></div></section>';
    break;
case 'product':
    $id=$_GET['id'] ?? '';
    if (!ctype_digit((string)$id)) {
        app_event('application_exception','application','error','Invalid product identifier exception; submitted identifier omitted.',['route'=>'product','owasp_category'=>'A10']);
        page_header('Product service exception', 'Catalog services', 'The product detail request could not be completed.');
        echo '<div class="error"><strong>Invalid product identifier</strong>\nInvalidArgumentException: product identifier must be an integer\n at CatalogRepository->find('.h($id).')\n at /var/www/vulnforge/app/controllers/ProductController.php:47\n debug_marker='.h(app_setting('exception_marker')).'</div><a class="button ghost" href="/?route=products">Return to catalog</a>';
    } else {
        $stmt=db()->prepare('SELECT * FROM products WHERE id=?');$stmt->execute([$id]);$p=$stmt->fetch();
        page_header($p['name'] ?? 'Product not found', 'Catalog item', $p ? 'Customer-ready item information and fictional list pricing.' : 'No catalog record matched this identifier.');
        if ($p) echo '<div class="grid two-column"><section class="card"><span class="pill">'.h($p['sku']).'</span><h2 style="margin-top:1rem">'.h($p['name']).'</h2><p>'.h($p['description']).'</p><dl class="detail-list"><div class="detail-row"><dt>List price</dt><dd class="amount">$'.h($p['price']).'</dd></div><div class="detail-row"><dt>Availability</dt><dd>'.status_badge('Active').'</dd></div><div class="detail-row"><dt>Fulfillment</dt><dd>Northstar warehouse network</dd></div></dl></section><section class="card"><h2>Sales support</h2><p>Use this product record when assisting fictional wholesale and retail teams.</p><a class="button ghost" href="/?route=products">Back to catalog</a></section></div>'; else echo '<section class="card"><div class="empty-state"><strong>Product not found</strong><span>No fictional product matches this catalog identifier.</span></div></section>';
    }
    break;
case 'search':
    $term=$_GET['term'] ?? '';
    if($term!=='') { $pattern=log_suspicious_parameter('term',$term,'search'); app_event('product_search','search','success','Portal search completed; query omitted, length='.strlen($term).' suspicious_pattern='.($pattern??'none'),['route'=>'search']); }
    page_header('Portal search', 'Knowledge and resources', 'Search public-facing Northstar portal text and internal navigation references.');
    echo '<form class="search-form"><input type="hidden" name="route" value="search"><div><label for="portal-term">Search portal content</label><input id="portal-term" name="term" value="'.h($term).'" placeholder="Search policies, teams, or tools"><span class="form-help">Results are generated by the installed fictional helper package.</span></div><button>Search portal</button></form>';
    if($term!=='') echo '<section class="card"><div class="card-header"><div><h2>Search result</h2><p>Matching portal response</p></div></div>'.Helper::renderGreeting($term).'<p class="muted">Result generated by fake-vendor/unsafe-helper 0.8.1.</p></section>'; else echo '<section class="card"><div class="empty-state"><strong>Start with a search term</strong><span>Enter a phrase above to search the fictional employee portal.</span></div></section>';
    break;
case 'vendor-demo':
    page_header('Dependency support console', 'IT engineering', 'Review installed helper package information and local support diagnostics.');
    echo '<section class="card"><div class="card-header"><div><h2>unsafe-helper</h2><p>Fictional rendering utility</p></div>'.status_badge('Active').'</div><dl class="detail-list"><div class="detail-row"><dt>Installed version</dt><dd><code>0.8.1</code></dd></div><div class="detail-row"><dt>Source</dt><dd>Bundled local vendor package</dd></div><div class="detail-row"><dt>External calls</dt><dd>None</dd></div></dl>';
    if(($_GET['debug'] ?? '')==='1') echo '<pre>'.h(Helper::debugBanner()).'</pre>'; else echo '<a class="button" href="/?route=vendor-demo&debug=1">Enable verbose support banner</a>';
    echo '</section>';
    break;
case 'invoices':
    $u=require_login();
    $stmt=db()->prepare('SELECT id,invoice_number,item_summary,amount,payment_status FROM invoices WHERE user_id=?');$stmt->execute([$u['id']]);$invoices=$stmt->fetchAll();
    page_header('My invoices', 'Finance', 'Review fictional purchase records associated with your Northstar employee account.');
    echo '<section class="card"><div class="card-header"><div><h2>Invoice history</h2><p>'.h(count($invoices)).' account record'.(count($invoices)===1?'':'s').'</p></div></div><div class="table-wrap"><table><thead><tr><th>Invoice</th><th>Description</th><th>Payment status</th><th>Amount</th></tr></thead><tbody>';
    foreach($invoices as $i) echo '<tr><td><a class="table-title" href="/?route=invoice&id='.$i['id'].'">'.h($i['invoice_number']).'</a><span class="table-subtitle">Northstar Outfitters</span></td><td>'.h($i['item_summary']).'</td><td>'.status_badge($i['payment_status']).'</td><td class="amount">$'.h($i['amount']).'</td></tr>';
    if (!$invoices) echo empty_table_row(4, 'No invoices on file', 'This fictional employee account has no invoice history.');
    echo '</tbody></table></div></section>';
    break;
case 'invoice':
    $u=require_login(); $stmt=db()->prepare('SELECT invoices.*,users.display_name FROM invoices JOIN users ON users.id=invoices.user_id WHERE invoices.id=?');$stmt->execute([$_GET['id']??0]);$i=$stmt->fetch();
    if($i){
        audit('invoice.view','invoice='.$i['id']);
        app_event('invoice_view','finance','success','Invoice viewed; invoice_id='.(int)$i['id'],['user'=>$u]);
        if((int)$i['user_id'] !== (int)$u['id']) app_event('invoice_idor_suspected','authorization','observed','Requested invoice owner does not match session user; invoice_id='.(int)$i['id'].' owner_user_id='.(int)$i['user_id'],['user'=>$u,'owasp_category'=>'A01']);
        page_header('Invoice '.$i['invoice_number'], 'Finance record', 'Fictional account transaction detail for internal review.');
        echo '<div class="grid two-column"><section class="card"><div class="card-header"><div><h2>Invoice summary</h2><p>Northstar Outfitters internal billing</p></div>'.status_badge($i['payment_status']).'</div><dl class="detail-list"><div class="detail-row"><dt>Account holder</dt><dd>'.h($i['display_name']).'</dd></div><div class="detail-row"><dt>Description</dt><dd>'.h($i['item_summary']).'</dd></div><div class="detail-row"><dt>Invoice total</dt><dd class="amount">$'.h($i['amount']).'</dd></div><div class="detail-row"><dt>Payment status</dt><dd>'.status_badge($i['payment_status']).'</dd></div></dl></section><aside class="card"><h2>Finance note</h2><p class="notice">'.h($i['private_note']).'</p><p class="muted">This record contains fictional data for authorized lab use only.</p><a class="button ghost" href="/?route=invoices">Back to invoices</a></aside></div>';
    } else { page_header('Invoice not found', 'Finance record', 'No fictional billing record matched this identifier.'); echo '<section class="card"><div class="empty-state"><strong>Invoice unavailable</strong><span>Return to your invoice history and select another record.</span></div></section>'; }
    break;
case 'support':
    $u=require_login(); $stmt=db()->prepare('SELECT id,subject,status,admin_only FROM support_tickets WHERE user_id=? AND admin_only=0');$stmt->execute([$u['id']]);$tickets=$stmt->fetchAll();
    page_header('Support tickets', 'Northstar service desk', 'Track fictional account, equipment, fulfillment, and access requests.');
    echo '<div class="grid"><section class="card stat-card"><span class="stat-label">Visible requests</span><span class="stat-value">'.h(count($tickets)).'</span><span class="stat-meta">Assigned to your account</span></section><section class="card stat-card"><span class="stat-label">Service channel</span><span class="stat-value">Portal</span><span class="stat-meta">No external service calls</span></section></div><section class="card"><div class="card-header"><div><h2>My request queue</h2><p>Latest fictional service desk activity</p></div>'.status_badge('Active').'</div><div class="table-wrap"><table><thead><tr><th>Ticket</th><th>Subject</th><th>Status</th><th>Action</th></tr></thead><tbody>';
    foreach($tickets as $t) echo '<tr><td><code>NS-'.str_pad((string)$t['id'], 5, '0', STR_PAD_LEFT).'</code></td><td><span class="table-title">'.h($t['subject']).'</span><span class="table-subtitle">Employee support request</span></td><td>'.status_badge($t['status']).'</td><td><a class="button ghost small" href="/?route=ticket&id='.$t['id'].'">View ticket</a></td></tr>';
    if (!$tickets) echo empty_table_row(4, 'No support tickets', 'There are no visible requests for this fictional account.');
    echo '</tbody></table></div></section>';
    break;
case 'ticket':
    $u=require_login(); $stmt=db()->prepare('SELECT * FROM support_tickets WHERE id=?');$stmt->execute([$_GET['id']??0]);$t=$stmt->fetch();
    $allowed=$t && ($t['user_id']==$u['id'] || $u['role_name']==='admin' || ($_GET['preview']??'')==='admin');
    if(!$allowed) { app_event('support_ticket_view','support','denied','Support ticket view denied; ticket_id='.(int)($_GET['id']??0),['user'=>$u]); page_header('Restricted support ticket', 'Northstar service desk', 'This request is not available in your current support queue.'); echo '<div class="error"><strong>Ticket access restricted.</strong><br>Return to your assigned requests or contact a fictional service desk administrator.</div><a class="button ghost" href="/?route=support">Back to support queue</a>'; }
    else { app_event('support_ticket_view','support','success','Support ticket viewed; ticket_id='.(int)$t['id'],['user'=>$u]); page_header('Ticket NS-'.str_pad((string)$t['id'], 5, '0', STR_PAD_LEFT), 'Northstar service desk', $t['subject']); echo '<div class="grid two-column"><section class="card"><div class="card-header"><div><h2>'.h($t['subject']).'</h2><p>Submitted through the employee portal</p></div>'.status_badge($t['status']).'</div><div class="timeline"><div class="timeline-item"><time>Request opened</time><strong>Employee submitted request</strong><p>'.h($t['body']).'</p></div><div class="timeline-item"><time>Support review</time><strong>Request assigned to service desk</strong><p>Status is currently '.h($t['status']).'.</p></div><div class="timeline-item"><time>Internal update</time><strong>Agent work note</strong><p>'.h($t['internal_note']).'</p></div></div></section><aside class="card"><h2>Request details</h2><dl class="detail-list"><div class="detail-row"><dt>Reference</dt><dd><code>NS-'.str_pad((string)$t['id'], 5, '0', STR_PAD_LEFT).'</code></dd></div><div class="detail-row"><dt>Status</dt><dd>'.status_badge($t['status']).'</dd></div><div class="detail-row"><dt>Channel</dt><dd>Employee portal</dd></div></dl><a class="button ghost" href="/?route=support">Back to queue</a></aside></div>'; }
    break;
case 'profile':
    $u=require_login();
    if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['bio'])) { $stmt=db()->prepare('UPDATE users SET profile_bio=? WHERE id=?');$stmt->execute([$_POST['bio'],$u['id']]);app_event('profile_update','account','success','Profile biography updated; content omitted.',['user'=>$u]);header('Location: /?route=profile');exit; }
    page_header('Employee profile', 'People directory', 'Manage the personal details and portability settings for your fictional Northstar account.');
    echo '<div class="grid two-column"><section class="card"><div class="profile-summary"><span class="profile-avatar">'.h(strtoupper(substr($u['display_name'],0,1))).'</span><div><h2>'.h($u['display_name']).'</h2><span class="pill">'.h($u['role_name']).'</span><p class="muted">'.h($u['email']).'</p></div></div><form method="post"><label for="display-name">Display name</label><input id="display-name" disabled value="'.h($u['display_name']).'"><span class="form-help">Managed by the fictional employee directory.</span><label for="bio">Directory biography</label><textarea id="bio" name="bio">'.h($u['profile_bio']).'</textarea><span class="form-help">Shown in internal Northstar collaboration views.</span><button>Save profile</button></form></section><aside class="card"><p class="eyebrow">Data portability</p><h2>Private note export</h2><p>Legacy reversible format used by this fictional profile service:</p><p><code>'.h($u['encoded_private_note']).'</code></p><dl class="detail-list"><div class="detail-row"><dt>Hash scheme</dt><dd><code>'.h($u['hash_scheme']).'</code></dd></div><div class="detail-row"><dt>Export format</dt><dd>Northstar profile JSON</dd></div></dl><a class="button secondary" href="/?route=profile-import">Import profile JSON</a></aside></div>';
    break;
case 'profile-import':
    $u=require_login();$result='';
    if($_SERVER['REQUEST_METHOD']==='POST') {
        $data=json_decode($_POST['profile_json']??'',true);
        if(is_array($data)) { $_SESSION['imported_role']=$data['role']??$u['role_name']; app_event('profile_import','account','success','Profile import accepted; imported document omitted.',['user'=>$u,'owasp_category'=>'A08']); $result='<div class="success">Profile document accepted. Effective imported role: <strong>'.h($_SESSION['imported_role']).'</strong></div>'; if(($_SESSION['imported_role'])==='admin') $result.='<p class="flag">'.h(app_setting('import_review_marker')).'</p>'; }
        else { app_event('profile_import','account','failure','Profile import rejected; imported document omitted.',['user'=>$u,'owasp_category'=>'A08']); $result='<div class="error">Invalid JSON. Check the profile document format and try again.</div>'; }
    }
    page_header('Profile import', 'Account settings', 'Restore a portable profile document exported by this fictional employee portal.');
    echo '<div class="grid two-column"><section class="card"><h2>Import profile document</h2>'.$result.'<form method="post"><label for="profile-json">Profile JSON</label><textarea id="profile-json" name="profile_json">{"display_name":"Guest Player","role":"guest"}</textarea><span class="form-help">Paste a Northstar-formatted profile document. Imported fields apply to this lab session.</span><button>Import profile</button></form></section><aside class="card"><h2>Import guidance</h2><p>Profile portability helps fictional staff move settings between isolated lab sessions.</p><div class="warning"><strong>Training implementation notice</strong><br>This legacy workflow accepts profile data without a signature.</div><a class="button ghost" href="/?route=profile">Back to profile</a></aside></div>';
    break;
case 'admin':
    $u=require_login();$effective=$_SESSION['imported_role']??$u['role_name'];
    if($effective!=='admin' && ($_GET['admin']??'')!=='1') { app_event('admin_access_denied','authorization','denied','Administrative console access denied.',['user'=>$u,'owasp_category'=>'A01']); page_header('Operations console', 'Administration', 'Restricted Northstar configuration and service controls.'); echo '<div class="error"><strong>Administrator role required.</strong><br>Your current effective role cannot access operations console widgets.</div>'; }
    else { app_event('admin_access','authorization','success','Administrative console viewed; effective_role='.telemetry_text((string)$effective,40),['user'=>$u,'owasp_category'=>'A01']); page_header('Operations console', 'Administration', 'Internal controls and service summaries for Northstar portal administrators.'); echo '<div class="grid"><section class="card admin-widget"><span class="stat-label">Effective role</span><span class="widget-number">'.h(ucwords($effective)).'</span><p class="muted">Current portal authorization context</p></section><section class="card admin-widget"><span class="stat-label">Application mode</span><span class="widget-number">Debug</span><p class="muted">Training diagnostics enabled</p></section><section class="card admin-widget"><span class="stat-label">Service scope</span><span class="widget-number">Local</span><p class="muted">No external providers connected</p></section></div><div class="grid two-column"><section class="card"><div class="card-header"><div><h2>Portal configuration</h2><p>Current fictional environment settings</p></div>'.status_badge('Active').'</div><div class="service-row"><div><strong>Debug mode</strong><span>Verbose training output</span></div>'.status_badge('Active').'</div><div class="service-row"><div><strong>Outbound mail</strong><span>Third-party delivery disabled</span></div>'.status_badge('Disabled').'</div><div class="service-row"><div><strong>Training marker</strong><span>'.h(app_setting('import_review_marker')).'</span></div>'.status_badge('Active').'</div></section><aside class="card"><h2>Administrative tools</h2><p>Review local security events, dependency output, and system status.</p><div class="button-row"><a class="button ghost" href="/?route=logs">Audit viewer</a><a class="button ghost" href="/?route=diagnostics">System status</a><a class="button ghost" href="/?route=vendor-demo">Dependencies</a></div></aside></div>'; }
    break;
case 'uploads':
    require_login();$msg='';
    if($_SERVER['REQUEST_METHOD']==='POST' && isset($_FILES['lab_file']) && $_FILES['lab_file']['error']===UPLOAD_ERR_OK) {
        $name=basename($_FILES['lab_file']['name']); $moved=move_uploaded_file($_FILES['lab_file']['tmp_name'],__DIR__.'/../uploads/'.$name); app_event('file_upload','file_exchange',$moved?'success':'failure','File upload processed; name='.telemetry_text($name,120).' size='.(int)($_FILES['lab_file']['size']??0).'; contents omitted.',['user'=>telemetry_user(),'owasp_category'=>'A08']);$msg=$moved?'<div class="success">Uploaded as <strong>'.h($name).'</strong>. Server-side execution is disabled in the Apache alias.</div>':'<div class="error" role="alert"><strong>Upload unsuccessful.</strong><br>The local file exchange could not store this document.</div>';
    }
    page_header('File exchange', 'Operations documents', 'Share fictional operational files within the isolated Northstar training environment.');
    echo '<div class="grid two-column"><section class="card"><h2>Upload a lab document</h2>'.$msg.'<form method="post" enctype="multipart/form-data"><label for="lab-file">Select document</label><div class="file-field"><input id="lab-file" type="file" name="lab_file" required><span class="form-help" data-file-name>No file selected</span></div><span class="form-help">Use only fake, non-sensitive training documents.</span><button>Upload document</button></form></section><aside class="card"><h2>Shared document library</h2><p>Browse files previously added to the local exchange directory, including lab metadata.</p><a class="button secondary" href="/uploads/">Browse shared uploads</a><div class="warning"><strong>Local lab storage</strong><br>Files remain inside this resettable environment. Do not upload real business data.</div></aside></div>';
    break;
case 'diagnostics':
    app_event('diagnostics_view','diagnostics','success','Diagnostics page viewed; detail='.(($_GET['detail']??'')==='1'?'true':'false'),['owasp_category'=>'A05']);
    page_header('System status', 'IT service operations', 'Local health and environment information for the Northstar employee portal.');
    echo '<div class="grid"><section class="card stat-card"><span class="stat-label">Overall status</span><span class="stat-value">Operational</span><span class="stat-meta">Local training services responding</span></section><section class="card stat-card"><span class="stat-label">Portal version</span><span class="stat-value">'.h(app_setting('portal_version')).'</span><span class="stat-meta">Northstar internal release</span></section><section class="card stat-card"><span class="stat-label">Environment</span><span class="stat-value">Private Lab</span><span class="stat-meta">Region '.h(app_setting('diagnostic_region')).'</span></section></div><section class="card"><div class="card-header"><div><h2>Service health</h2><p>Current component availability</p></div>'.status_badge('Operational').'</div><div class="service-row"><div><strong>Employee portal</strong><span>Web application and session service</span></div>'.status_badge('Reachable').'</div><div class="service-row"><div><strong>Catalog database</strong><span>Fictional products and account records</span></div>'.status_badge('Reachable').'</div><div class="service-row"><div><strong>Outbound mail</strong><span>Disabled by private-lab policy</span></div>'.status_badge('Disabled').'</div><div class="service-row"><div><strong>Network boundary</strong><span>Bind: 127.0.0.1:8080</span></div>'.status_badge('Active').'</div></section>';
    if(($_GET['detail']??'')==='1') echo '<section class="card"><h2>Detailed environment output</h2><pre>APP_ENV=training\nAPP_DEBUG=true\nDB_HOST=localhost\nDOCUMENT_ROOT=/var/www/vulnforge/public\n'.h(app_setting('debug_marker')).'</pre></section>'; else echo '<a class="button" href="/?route=diagnostics&detail=1">View detailed diagnostics</a>';
    break;
case 'command-console':
    $input=$_GET['check']??'status';$out=[];
    // Intentionally injectable command grammar, but no OS shell is called. Only these fixed fake-data operations exist.
    foreach(preg_split('/\s*;\s*/',$input) as $cmd){ if($cmd==='status')$out[]='orders: ok';elseif($cmd==='count')$out[]='fake records: 4';elseif($cmd==='show marker')$out[]=app_setting('command_marker');else $out[]='unknown simulated command: '.$cmd; }
    page_header('Warehouse command console', 'IT diagnostics', 'Run bounded, simulated health operations against fixed fictional warehouse data.');
    echo '<div class="grid two-column"><section class="card"><div class="info"><strong>Simulation safety boundary</strong><br>This interpreter never invokes the operating-system shell and can only read fixed fake lab values.</div><form><input type="hidden" name="route" value="command-console"><label for="health-check">Health operation</label><input id="health-check" name="check" value="'.h($input).'"><span class="form-help">Supported operations include status and count.</span><button>Run diagnostic</button></form><h2 style="margin-top:1.5rem">Console output</h2><pre>'.h(implode("\n",$out)).'</pre></section><aside class="card"><h2>Tool information</h2><dl class="detail-list"><div class="detail-row"><dt>Execution</dt><dd>Simulated only</dd></div><div class="detail-row"><dt>Data scope</dt><dd>Fixed fictional values</dd></div><div class="detail-row"><dt>Shell access</dt><dd>None</dd></div></dl></aside></div>';
    break;
case 'refund':
    $result='';if($_SERVER['REQUEST_METHOD']==='POST'){app_event('refund_request','finance','observed','Refund estimate requested; submitted values omitted.',['user'=>telemetry_user(),'owasp_category'=>'A06']);$qty=(int)($_POST['quantity']??0);$code=$_POST['coupon']??'';$stmt=db()->prepare('SELECT * FROM coupons WHERE code=?');$stmt->execute([$code]);$c=$stmt->fetch();if($c){$refund=20*$qty*(1+$c['percent_off']/100);$result='<div class="success">Calculated fictional refund: <strong>$'.h(number_format($refund,2)).'</strong></div>';if($qty<0)$result.='<p class="flag">'.h($c['internal_note']).'</p>';}}
    page_header('Refund estimator', 'Finance operations', 'Estimate a fictional return adjustment before sending it to the retail support team.');
    echo '<div class="grid two-column"><section class="card"><h2>Estimate return value</h2>'.$result.'<form method="post"><label for="quantity">Quantity returned</label><input id="quantity" type="number" name="quantity" value="1"><span class="form-help">Enter the number of fictional units included in the return.</span><label for="coupon">Promotion code</label><input id="coupon" name="coupon" value="WELCOME10"><span class="form-help">Applicable promotional adjustments are included in the estimate.</span><button>Calculate estimate</button></form></section><aside class="card"><h2>Workflow note</h2><p>Estimates are for internal review and do not contact a payment provider or issue a real refund.</p>'.status_badge('In Review').'</aside></div>';
    break;
case 'password-reset':
    $result=''; if($_SERVER['REQUEST_METHOD']!=='POST') app_event('password_reset_request','authentication','observed','Password reset verification page viewed; no token logged.'); if($_SERVER['REQUEST_METHOD']==='POST'){$stmt=db()->prepare('SELECT password_resets.*,users.email FROM password_resets JOIN users ON users.id=password_resets.user_id WHERE token=?');$stmt->execute([$_POST['token']??'']);$r=$stmt->fetch();if($r){app_event('password_reset_complete','authentication','success','Password reset token verified; token value omitted.');$result='<div class="success">Token accepted for '.h($r['email']).'. Training marker: '.h(app_setting('reset_marker')).'</div>';}else{app_event('password_reset_complete','authentication','failure','Password reset token rejected; token value omitted.');$result='<div class="error">Unknown token. Confirm the fictional reset reference and try again.</div>';} }
    page_header('Password reset verification', 'Account recovery', 'Verify a local reset reference for a fictional Northstar employee account.');
    echo '<div class="grid two-column"><section class="card"><h2>Verify reset request</h2>'.$result.'<form method="post"><label for="reset-token">Reset token</label><input id="reset-token" name="token" placeholder="reset-userid-year"><span class="form-help">Enter the full reference from the local training workflow.</span><button>Verify token</button></form></section><aside class="card"><h2>Delivery notice</h2><p>No email is sent and this lab contacts no third parties. All recovery data is fictional and local.</p><div class="info">For training support, consult the player guide rather than a real helpdesk.</div></aside></div>';
    break;
case 'logs':
    $u=require_login();$logs=db()->query('SELECT * FROM audit_logs ORDER BY created_at DESC')->fetchAll();
    page_header('Audit log viewer', 'Security operations', 'Review selected local portal events captured for the fictional Northstar environment.');
    echo '<div class="warning"><strong>Coverage notice</strong><br>This viewer omits failed authentication, profile imports, and effective-role changes.</div><section class="card"><div class="card-header"><div><h2>Recorded activity</h2><p>'.h(count($logs)).' event'.(count($logs)===1?'':'s').' in the current lab state</p></div></div><div class="table-wrap"><table><thead><tr><th>Timestamp</th><th>Event</th><th>Details</th></tr></thead><tbody>';
    foreach($logs as $l)echo '<tr><td><span class="table-title">'.h($l['created_at']).'</span><span class="table-subtitle">Local server time</span></td><td><code>'.h($l['event_type']).'</code></td><td>'.h($l['details']).'</td></tr>';
    if (!$logs) echo empty_table_row(3, 'No audit events recorded', 'Activity captured by this intentionally incomplete viewer will appear here.');
    echo '</tbody></table></div></section>';
    if(($_GET['compare']??'')==='1')echo '<p class="flag">'.h(app_setting('logging_gap_marker')).'</p>';else echo '<a class="button" href="/?route=logs&compare=1">Compare expected security events</a>';
    break;
case 'scoreboard':
    $u=require_login();$message='';if($_SERVER['REQUEST_METHOD']==='POST') {[$ok,$text]=submit_flag($u,$_POST['flag']??'');$message='<div class="'.($ok?'success':'error').'">'.h($text).'</div>';}
    $total=(int)db()->query('SELECT COUNT(*) FROM flags')->fetchColumn();$stmt=db()->prepare('SELECT COUNT(*) FROM submissions WHERE user_id=?');$stmt->execute([$u['id']]);$solved=(int)$stmt->fetchColumn();$pct=$total?(int)(100*$solved/$total):0;
    page_header('Security readiness scoreboard', 'Training progress', 'Track your authorized exploration of the Northstar portal across OWASP Top 10:2025 categories.');
    echo $message.'<section class="card"><div class="score-summary"><div class="score-number">'.h($solved).'/'.h($total).'</div><div><p class="eyebrow">Individual progress</p><h2>'.h($pct).'% of objectives discovered</h2><div class="progress" aria-label="'.h($pct).'% complete"><span style="width:'.$pct.'%"></span></div><p class="muted">Progress is stored for '.h($u['display_name']).' in this resettable lab.</p></div></div><form method="post"><label for="flag">Submit a training flag</label><div class="form-row"><div><input id="flag" name="flag" placeholder="FLAG{CATEGORY_DESCRIPTION_01}" required><span class="form-help">Flags are case-sensitive and use the format shown above.</span></div><div><button type="submit" style="margin-top:0">Record discovery</button></div></div></form></section><section class="card"><div class="card-header"><div><h2>Objective register</h2><p>Two training objectives in each OWASP category</p></div><span class="pill">20 total</span></div><div class="table-wrap"><table><thead><tr><th>Category</th><th>Business scenario</th><th>Difficulty</th><th>Progress</th></tr></thead><tbody>';
    $stmt=db()->prepare('SELECT flags.*,submissions.id solved FROM flags LEFT JOIN submissions ON submissions.flag_id=flags.id AND submissions.user_id=? ORDER BY flags.category,flags.id');$stmt->execute([$u['id']]);foreach($stmt as $f)echo '<tr><td><code>'.h($f['category']).'</code></td><td><span class="table-title">'.h($f['challenge_name']).'</span><span class="table-subtitle">Northstar portal workflow</span></td><td><span class="pill">'.h($f['difficulty']).'</span></td><td>'.status_badge($f['solved']?'Discovered':'Undiscovered').'</td></tr>';echo '</tbody></table></div></section>';
    break;
case 'changelog':
    page_header('Portal release notes', 'IT engineering', 'Internal updates and pilot features in the fictional Northstar training environment.');
    echo '<section class="card"><div class="card-header"><div><h2>Release 0.9.4-lab</h2><p>Current local portal build</p></div>'.status_badge('Active').'</div><div class="timeline"><div class="timeline-item"><time>Finance services</time><strong>Fictional invoice API added</strong><p>Internal billing integrations can now retrieve local training records.</p></div><div class="timeline-item"><time>IT engineering</time><strong>Dependency support tools enabled</strong><p>Review the <a href="/?route=vendor-demo">dependency support console</a> for package details.</p></div><div class="timeline-item"><time>Warehouse operations</time><strong>Diagnostics pilot underway</strong><p>The team is testing a bounded <a href="/?route=command-console">local command console</a> and <a href="/?route=refund">refund estimator</a>.</p></div><div class="timeline-item"><time>Security review</time><strong>Identity and audit workflows under review</strong><p>Engineering is evaluating the <a href="/?route=password-reset">reset verifier</a> and <a href="/?route=logs">audit viewer</a>.</p></div></div></section>';
    break;
default:
    http_response_code(404);echo '<section class="error-page"><span class="error-code">404</span><p class="eyebrow">Page not found</p><h1>This trail ends here.</h1><p>The requested Northstar portal page is unavailable. Use the main navigation or return to your workspace.</p><div class="button-row" style="justify-content:center"><a class="button" href="/?route=home">Return home</a><a class="button ghost" href="/?route=dashboard">Open dashboard</a></div></section>';
}
render_footer();
